// <auto-generated />
using CineSwipe.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineSwipe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CineSwipe.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Drama",
                            PosterUrl = "https://posters.movieposterdb.com/11_08/1994/111161/s_111161_e9ccda65.jpg",
                            Rating = 9.3000000000000007,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Crime",
                            PosterUrl = "https://posters.movieposterdb.com/22_12/1991/809433/s_the-godfather-movie-poster_d53af75d.jpg",
                            Rating = 9.1999999999999993,
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action",
                            PosterUrl = "https://posters.movieposterdb.com/12_06/2011/2258647/l_2258647_c0830db9.jpg",
                            Rating = 9.0,
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Crime",
                            PosterUrl = "https://posters.movieposterdb.com/25_11/1994/110912/s_pulp-fiction-movie-poster_f099050c.jpg",
                            Rating = 8.9000000000000004,
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Drama",
                            PosterUrl = "https://posters.movieposterdb.com/12_04/1994/109830/s_109830_58524cd6.jpg",
                            Rating = 8.8000000000000007,
                            Title = "Forrest Gump"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Sci-Fi",
                            PosterUrl = "https://posters.movieposterdb.com/10_06/2010/1375666/l_1375666_07030c72.jpg",
                            Rating = 8.8000000000000007,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Sci-Fi",
                            PosterUrl = "https://posters.movieposterdb.com/06_01/1999/0133093/s_77607_0133093_ab8bc972.jpg",
                            Rating = 8.6999999999999993,
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Crime",
                            PosterUrl = "https://posters.movieposterdb.com/05_09/1990/0099685/s_54529_0099685_307a5bd2.jpg",
                            Rating = 8.6999999999999993,
                            Title = "Goodfellas"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Sci-Fi",
                            PosterUrl = "https://posters.movieposterdb.com/14_09/2014/816692/s_816692_593eaeff.jpg",
                            Rating = 8.5999999999999996,
                            Title = "Interstellar"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Thriller",
                            PosterUrl = "https://posters.movieposterdb.com/21_02/1991/102926/s_102926_90bd926b.jpg",
                            Rating = 8.5999999999999996,
                            Title = "The Silence of the Lambs"
                        });
                });

            modelBuilder.Entity("CineSwipe.Models.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WatchlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
